save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  
  # Update specific data
  update_target: "$.message.update_target"
  cancellation_reason: "$.message.order.cancellation.reason"
  
  # Updated item quantities (for partial cancellation confirmation)
  updated_items: "$.message.order.items[*]"