
  order:
    items:
    - id: I1
      parent_item_id: I0
      quantity:
        selected:
          count: 1
      add_ons:
      - id: A1
        quantity:
          selected:
            count: 1
      xinput:
        form:
          id: F01
        form_response:
          status: SUCCESS
          submission_id: F01_SUBMISSION_ID
    - id: I2
      parent_item_id: I0
      quantity:
        selected:
          count: 1
      add_ons:
      - id: A1
        quantity:
          selected:
            count: 1
      xinput:
        form:
          id: F01
        form_response:
          status: SUCCESS
          submission_id: F01_SUBMISSION_ID
    - id: I5
      parent_item_id: I0
      quantity:
        selected:
          count: 1
    fulfillments:
    - id: F1
      stops:
      - type: START
        time:
          timestamp: '2024-06-28T05:00:16.000Z'
    provider:
      id: P1
