flows:
  - id: incremental_pull_journey
    description: Incremental Pull flow with repeated on_search steps
    sequence:
      - key: search_incremental_pull
        type: search
        unsolicited: false
        pair: on_search_incremental_pull_1
        owner: BAP
        expect: true
        input:
          - name: city_code
            label: Enter city code
            type: text
            payloadField: $.message.intent.fulfillment.stops[?(@.type=='START')].location.city.code
      - key: on_search_incremental_pull_1
        type: on_search
        unsolicited: false
        pair: null
        owner: BPP
        expect: false
      - key: on_search_incremental_pull_2
        type: on_search
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
      - key: on_search_incremental_pull_3
        type: on_search
        unsolicited: true
        pair: null
        owner: BPP
        expect: false
