order:
  items:
    - id: I1
      quantity:
        selected:
          count: 1
  fulfillments:
    - id: F1
      stops:
        - type: START
          time:
            timestamp: '2024-06-28T05:00:16.000Z'
  provider:
    id: P1
  payments:
    - id: PA1
      collected_by: BAP
      status: NOT-PAID
      type: PRE-ORDER
  tags:
    - descriptor:
        code: BAP_TERMS
        name: BAP Terms of Engagement
      display: false
      list:
        - descriptor:
            code: BUYER_FINDER_FEES_PERCENTAGE
          value: '1'
        - descriptor:
            code: BUYER_FINDER_FEES_TYPE
          value: percent
        - descriptor:
            code: STATIC_TERMS
          value: https://api.example-bap.com/booking/terms
        - descriptor:
            code: SETTLEMENT_BASIS
          value: https://api.example-bap.com/booking/terms
        - descriptor:
            code: SETTLEMENT_WINDOW
          value: P30D 