
order:
  provider:
    id: P1
    descriptor:
      name: Unreserved Entry Pass
      images:
      - url: https://api.unreserved-entry-pass.com/sites/default/files/event/logo/event_logo_2.png
        size_type: xs
    locations:
    - id: L1
      gps: 28.524596, 77.185577
      descriptor:
        name: Qutab Minar
        short_desc: Seth Sarai, Mehrauli, New Delhi, Delhi. The Qutb Minar, also
          spelled Qutub Minar and Qutab Minar, is a minaret and "victory tower"
          that forms part of the Qutb complex
        additional_desc:
          url: https://api.unreserved-entry-pass.com/sites/additional-info
          content_type: text/plain
        images:
        - url: https://api.unreserved-entry-pass.com/sites/images/location.png
          size_type: md
      rating: '5'
  cancellation_terms:
  - cancellation_fee:
      percentage: '10'
    fulfillment_state:
      descriptor:
        code: CONFIRMED
    cancel_by:
      label: DURATION
      duration: PT1H30M
    cancellation_eligible: true
  - external_ref:
      mimetype: text/html
      url: https://api.unreserved-entry-pass.com/beckn/tnc.html
    cancellation_eligible: true
  replacement_terms:
  - external_ref:
      mimetype: text/html
      url: https://api.unreserved-entry-pass.com/beckn/replacement.html


