save-data:
  message_id: "$.context.message_id"
  transaction_id: "$.context.transaction_id"
  
  # Order status after soft cancellation
  order_status_partial_cancel: "$.message.order.status"
  
  # Updated order data after partial cancellation
  items_partial_cancel: "$.message.order.items[*]"
  quote_partial_cancel: "$.message.order.quote"
  
  # Keep existing order data
  order_id: "$.message.order.id"
  fulfillments: "$.message.order.fulfillments[*]"
  provider: "$.message.order.provider"
  billing: "$.message.order.billing"
  payments: "$.message.order.payments[*]"
  
  # Terms and policies
  cancellation_terms: "$.message.order.cancellation_terms[*]"
  replacement_terms: "$.message.order.replacement_terms[*]"
  tags: "$.message.order.tags[*]"
  
  # Timestamps
  created_at: "$.message.order.created_at"
  updated_at: "$.message.order.updated_at"